version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_mvc
    restart : always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mvc
    volumes:
      - db_data:/var/lib/postgresql/data

  dbadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    restart : always
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html

volumes:
  db_data:
  pgadmin_data:


