
# Use the official PHP image as the base image
FROM php:7.4-apache

# Install the necessary PHP extensions
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Install MySQL client
RUN apt-get update && apt-get install -y default-mysql-client

# Set the working directory to /var/www/html
WORKDIR /var/www/html

# Copy the PHP application files to the container
COPY . /var/www/html

# Expose port 80 for Apache
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]
