version: '3.8'

services:
  apache:
    image: httpd:latest
    volumes:
      - .:/usr/local/apache2/htdocs
    ports:
      - "80:80"
      
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: creuse-ton-parti
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
        - "5430:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
        - "8080:80"
    depends_on:
        - postgres

volumes:
  postgres-data:
  data: {}
