<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>User List</title>
</head>
<body>
  <h1>User List</h1>
  <?php if (isset($_SESSION['success_message'])): ?>
      <div class="alert alert-success">
          <?= $_SESSION['success_message']; ?>
      </div>
      <?php unset($_SESSION['success_message']); ?>
  <?php endif; ?>

  <a href="/user/add">Créer un Utilisateur</a> 

  <ul>
    <?php
    if($users != null or !(isset($users))){
        foreach ($users as &$value) {?>
            <li>
                <strong>Username:</strong> <?= $value->getUsername() ?><br>
                <strong>Birthdate:</strong> <?= $value->getBirthDate() ?><br>
                <strong>Password:</strong><?= $value->getPassword() ?><br>
                <a href="/user/update/<?= $value->getId() ?>">Modifier</a> 
                <a href="/user/delete/<?= $value->getId() ?>">supprimer</a>

            </li>
    <?php }
    }?>
  </ul>
</body>
</html>
