<!DOCTYPE html>
<html>
<head>
    <title>Update  User</title>
</head>
<body>

    <h2>Update <?= $user->getId() ?> User</h2>

    <form action="#" method="POST">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required value="<?= $user->getUsername() ?>"><br><br>

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required value="<?= $user->getPassword() ?>"><br><br>
        
        <label for="birthdate">Birthdate:</label>
        <input type="date" id="birthdate" name="birthdate" required value="<?= $user->getBirthDate() ?>"><br><br>
        <input type="hidden" name="_method" value="PUT">
        <input type="submit" value="Submit">
    </form>

</body>
</html>
